### ISSUE TITLE
Do not print the log message when the message content has quote ( ' )

### ISSUE THREAD

**Issue by spidermanja** [teragrep/jsa_01#5]
Sample message:
logger.fatal("Don’t test it as a NASA application")

**Comment by spidermanja** [comment]
Seems the message content has the unicode character ' (U+2019 RIGHT SINGLE QUOTATION MARK) not quote, that is not permitted to print the log message, but
logger.fatal("Don't test it as a NASA application");  ✅ this is working fine.

**Comment by kortemik** [comment]
I think it should support utf-8 in the message part.

**Comment by spidermanja** [comment]
Fixed with RLO_08 V1.0.2 for utf8 support
